#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyterlab/toc @jupyterlab/geojson-extension jupyterlab_bokeh jupyterlab-drawio jupyterlab_voyager jupyterlab_vim
